services:
  postgres:
    image: postgres:16-alpine
    container_name: odoocafe-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoocafe
      POSTGRES_PASSWORD: odoocafe123
      POSTGRES_DB: odoocafe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
